// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ATable: typeof import('ant-design-vue/es')['Table']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    ChapterList: typeof import('./src/components/ChapterList.vue')['default']
    ChapterManagerModal: typeof import('./src/components/ChapterManagerModal.vue')['default']
    ClassificationManagerModal: typeof import('./src/components/ClassificationManagerModal.vue')['default']
    CourseItem: typeof import('./src/components/CourseItem.vue')['default']
    CourseList: typeof import('./src/components/CourseList.vue')['default']
    CourseManagerModal: typeof import('./src/components/CourseManagerModal.vue')['default']
    CtsButton: typeof import('./src/components/CtsButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListSelector: typeof import('./src/components/ListSelector.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserManagerModal: typeof import('./src/components/UserManagerModal.vue')['default']
    VerticalClassificationMenu: typeof import('./src/components/VerticalClassificationMenu.vue')['default']
  }
}
